name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Elm
        uses: JorelAli/setup-elm@v3

      - name: Setup Node
        uses: actions/setup-node@v2.5.1

      - name: npm install
        run: npm install

      - name: Install elm-test
        run: npm install -g elm-test@0.19.1-revision7

      - name: Run elm-coverage
        run: npx elm-coverage -r codecov

      - name: Upload to codecov  
        uses: codecov/codecov-action@v2.1.0
        with:
          file: .coverage/codecov.json

      - name: Run elm-spec
        run: npx elm-spec

      - name: Compile examples
        run: elm make *.elm
        working-directory: ./examples
