name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Elm
        uses: justgook/setup-elm@v1
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: elm-test
        run: npx elm-coverage
      - name: Upload Coverage as Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: Coverage
          # Directory containing files to upload
          path: .coverage/coverage.html
