name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Elm
        uses: justgook/setup-elm@v1

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: npm install
        run: npm install

      - name: Install elm-test
        run: npm install -g elm-test@0.19.1-revision2

      - name: Run elm-coverage
        run: npx elm-coverage -r codecov

      - name: Upload to codecov  
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .coverage/codecov.json

      - name: Run elm-spec
        run: npx elm-spec

      - name: Compile examples
        run: elm make *.elm
        working-directory: ./examples
