name: CI

on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Elm
        uses: justgook/setup-elm@v1      
      - name: Build example
        run:  elm make Simple.elm --output=../docs/index.html
        working-directory: ./examples
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          target_branch: gh-pages
          allow_empty_commit: false
          build_dir: ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
