name: CI

on:
  push:
    branches:
      - master    
    paths-ignore:
    - 'docs/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Elm
        uses: justgook/setup-elm@v1      
      - name: Build example
        run:  elm make Simple.elm --output=../docs/index.html
        working-directory: ./examples
      - name: Git Commit on Workflow
        uses: matheusalbino/git-commit@v1.0.1
        with:
          github-token : ${{ secrets.GITHUB_TOKEN }}
          message: Update Documentation
